"""
gen_sleep_configs.py -- appends paired sleep configs to a scenario07 ini.

    SEED=22 python3 gen_sleep_configs.py

Produces, for each tx power in {37, 43, 46} and each gNB k in 0..3:
    Scenario07s{SEED}_p{P}_sleep{k}
which is the ordinary run with gNB k's transmit power forced to 1 dBm,
so its UEs hand over to neighbours and it serves nobody.

Why paired full-run sleep, and not a mid-run schedule
-----------------------------------------------------
`eNodeBTxPower` is read once in LtePhyBase::initialize (line 42) into
eNodeBtxPower_, copied to txPower_ in LtePhyEnb (line 60), and there is
NO handleParameterChange anywhere in the PHY -- verified by grep. So a
mid-run <set-param> from ScenarioManager would change the parameter
object and nothing else: the PHY keeps transmitting at the cached
value. Scheduled sleep is therefore impossible without patching the
simulator.

Paired runs give the same thing more cleanly. Same seed, same UE
trajectories, same traffic schedule, one difference: gNB k is off.
Comparing the pair gives, for an identical network state, measured
energy and measured delay/jitter/loss both with the cell serving and
with it asleep. The load did not cause the sleep -- it was imposed --
which is exactly the correlation that has to be broken for CMOA to be
trainable. Nothing is imputed; the neighbours genuinely absorb the
traffic and the handovers genuinely happen.

Verified on scenario07 seed 22 p43 before writing this: with
`*.gnb2.cellularNic.phy.eNodeBTxPower = 1dBm`, serving-cell value 3
(= gnb2) disappears entirely after t=30s and UEs redistribute to cells
1, 2 and 4. The module path is confirmed correct -- worth stating
because OMNeT++ accepts a path matching no module without complaint,
which would leave the "sleeping" gNB transmitting at full power and
produce plausible but meaningless data.

Why scenario07 (4 gNB) and not scenario06b (6 gNB)
--------------------------------------------------
scenario06b is already saturated (200-2000ms delays, up to 16 UEs on a
cell). Sleeping a cell there collapses the neighbours, so every example
would read "catastrophic" and CMOA would learn only "never sleep".
scenario07 has headroom, so sleeping gives a GRADIENT: sometimes the
neighbours cope and ~260W is saved for free, sometimes QoS breaks and
the action should be rejected. A verification loop needs both.

1 dBm rather than 0: keeps the cell nominally alive (no division by
zero in path-loss maths) while making it unusable to any UE. Its energy
label still comes from the extractor's model, which reports the idle
floor when a cell serves nothing.
"""

import os

SEED = int(os.environ.get("SEED", "22"))
POWERS = (37, 43, 46)
NUM_GNB = 4
SLEEP_DBM = 1

src = f"omnetpp_s{SEED}.ini"
if not os.path.exists(src):
    raise SystemExit(f"{src} not found -- run from the scenario07 folder")

text = open(src).read()

marker = f"# --- sleep configs (generated by gen_sleep_configs.py) ---"
if marker in text:
    text = text.split(marker)[0].rstrip() + "\n"
    print("removed previous sleep configs (idempotent re-run)")

lines = [text.rstrip(), "", marker, ""]
n = 0
for p in POWERS:
    for k in range(NUM_GNB):
        cfg = f"Scenario07s{SEED}_p{p}_sleep{k}"
        lines.append(f"[Config {cfg}]")
        lines.append(f"extends = Scenario07s{SEED}_p{p}")
        lines.append(f"*.gnb{k}.cellularNic.phy.eNodeBTxPower = {SLEEP_DBM}dBm")
        lines.append("")
        n += 1

open(src, "w").write("\n".join(lines))
print(f"appended {n} sleep configs to {src}")
print(f"  baseline configs (already present): "
      f"{', '.join(f'Scenario07s{SEED}_p{p}' for p in POWERS)}")
print(f"  sleep configs: Scenario07s{SEED}_p{{37,43,46}}_sleep{{0..{NUM_GNB-1}}}")
print()
print("Run them with run_sleep.sh, then verify EVERY sleep run actually")
print("lost its cell before extracting -- a silently-mismatched parameter")
print("path is the failure mode that produces believable but wrong data.")
