"""
make_gen_dense.py -- derives gen_ini_dense.py from gen_ini.py.

    python3 make_gen_dense.py
    SEED=61 python3 gen_ini_dense.py

WHY A DENSE DEPLOYMENT
----------------------
Three components of the contribution deck were tested in the 1 km-spacing
scenario07 deployment and none helped:
  - E2 interference edges, static distance feature      (5 seeds, no effect)
  - E2 interference edges, dynamic SINR-delta feature   (no effect)
  - Encoder depth 2 -> 4 message-passing rounds         (no effect)
All three represent INTER-CELL information, and the consistent physical
reading is that at 1 km inter-site distance with 50 RBs and PF
scheduling, inter-cell coupling does not drive uplink delay -- intra-cell
contention does, and E1 already captures it.

This scenario tests whether that conclusion is deployment-specific
rather than general. At 300 m spacing a neighbouring cell is ~10.5 dB
stronger as an interferer (20*log10(1000/300)), so cells genuinely
overlap and a UE's performance should depend on neighbours' load. If
E2 and depth still add nothing here, the negative result is much
stronger. If they help, the finding becomes conditional on density,
which is more interesting than either component simply working.

Framing matters: this is NOT "change the scenario until the architecture
looks good". Both regimes get reported. The sparse-deployment negatives
stand regardless of what this shows.

WHAT CHANGES, AND WHAT DELIBERATELY DOES NOT
--------------------------------------------
Changed:
  - gNB grid 1000 m -> 300 m spacing, area 2000x2000 -> 1000x1000 m
  - UE spawn range narrowed to match the smaller area
  - config/file names -> Scenario09*

Unchanged, so the comparison isolates density:
  - 4 gNBs, 30 UEs, 50 RBs, PF scheduling, handover enabled
  - UE speed 3-8 m/s, LinearMobility, reflect at borders
  - the 40-phase L/M/H traffic schedule and QoS packet sizes
  - three tx powers (37/43/46 dBm)
  - RNG draw order, so the extraction replay works unchanged

EXPECTED RISK: handover frequency scales with density, and the Simu5G
NrMacGnb handover race scales with handover frequency (20/21 runs
completed at 1 km, 2/28 at 8 gNB / 80 UE). Crashes here are likely. If
most runs fail, lowering UE speed to 1-3 m/s is the fallback -- it cuts
handover rate while preserving the density that makes interference
matter. That would cost comparability on speed, and must be documented.

The extraction script needs MAP_SIZE changed 2000 -> 1000 and the UE
spawn range matched, or every reconstructed position will be wrong.
"""

import os

SRC = "gen_ini.py"
DST = "gen_ini_dense.py"

if not os.path.exists(SRC):
    raise SystemExit(f"{SRC} not found -- run from the scenario07 folder")

s = open(SRC).read()

# 300 m spacing, 2x2 grid centred in a 1000x1000 m area.
subs = [
    ("GNB_POSITIONS = {0: (500,500), 1: (1500,500), 2: (500,1500), 3: (1500,1500)}",
     "GNB_POSITIONS = {0: (350,350), 1: (650,350), 2: (350,650), 3: (650,650)}"),
    ("**.mobility.constraintAreaMaxX = 2000m",
     "**.mobility.constraintAreaMaxX = 1000m"),
    ("**.mobility.constraintAreaMaxY = 2000m",
     "**.mobility.constraintAreaMaxY = 1000m"),
    ("x = random.uniform(200, 1800)", "x = random.uniform(100, 900)"),
    ("y = random.uniform(200, 1800)", "y = random.uniform(100, 900)"),
    ('CFG = f"Scenario07s{SEED}"', 'CFG = f"Scenario09s{SEED}"'),
    ("f'omnetpp_s{SEED}.ini'", "f'omnetpp_dense{SEED}.ini'"),
    ("f'ue_assignment_s{SEED}.txt'", "f'ue_assignment_dense{SEED}.txt'"),
]

missing = []
for old, new in subs:
    if old not in s:
        missing.append(old)
    else:
        s = s.replace(old, new)

if missing:
    print("PATTERNS NOT FOUND -- gen_ini.py differs from what was expected:")
    for m in missing:
        print(f"  {m}")
    raise SystemExit("aborted, nothing written")

header = '''"""
gen_ini_dense.py -- scenario09: 4 gNB / 30 UE at 300 m inter-site
distance (scenario07 is 1000 m). Everything else identical, so the
tested variable is DEPLOYMENT DENSITY.

Purpose: scenario07 found E2 interference edges (twice) and encoder
depth to add nothing, all three being inter-cell mechanisms. At 300 m a
neighbour is ~10.5 dB stronger as an interferer, so cells genuinely
overlap. This tests whether those negatives are deployment-specific.

Generated by make_gen_dense.py from gen_ini.py -- do not edit by hand,
edit the patcher so the derivation stays reproducible.
"""
'''
s = header + s

open(DST, "w").write(s)
print(f"wrote {DST}")
print()
print("gNB grid:  (350,350) (650,350) (350,650) (650,650) -- 300 m spacing")
print("area:      1000 x 1000 m")
print("UE spawn:  uniform(100, 900)")
print("configs:   Scenario09s{SEED}_p{37,43,46}")
print()
print("Next:")
print("  SEED=61 python3 gen_ini_dense.py")
print("  simu5g -f omnetpp_dense61.ini -c Scenario09s61_p43 -u Cmdenv")
print()
print("Run ONE simulation before generating more seeds -- denser cells mean")
print("more handovers, and the NrMacGnb race scales with handover rate.")
